---
# tasks file for ansible-role-win-sqlservermanagementstudio
- name: Ensure extract dir exists
  ansible.windows.win_file:
    path: '{{ sql_server_mgmt_extract_dir }}'
    state: directory

- name: Download SQL Managment Studio
  ansible.windows.win_get_url:
    url: '{{ sql_server_mgmt_download_url }}'
    dest: '{{ sql_server_mgmt_extract_dir }}\{{ sql_server_mgmt_install_exe }}'
    validate_certs: '{{ sql_server_mgmt_download_validate_certs }}'
    force: no

- name: Execute SQL Managment Studio Setup
  ansible.windows.win_command: '{{ sql_server_mgmt_extract_dir }}\{{ sql_server_mgmt_install_exe }} /install /quiet /norestart'
  args:
    creates: '{{ sql_server_mgmt_already_installed_path }}'
  register: sql_mgmt_setup_result

- name: Debug sql_mgmt_setup_result
  ansible.builtin.debug:
    var: sql_mgmt_setup_result

- name: Remove extract dir
  ansible.windows.win_file:
    path: '{{ sql_server_mgmt_extract_dir }}'
    state: absent
